### ISSUE TITLE
gets stuck on ID file reload and missing timeout when opening MMDVM

### ISSUE THREAD

**Issue by iddq** [g4klx/MMDVMHost#706]
Hello,

The communication stops sometimes when ID file reloaded.
no timeout for opening the MMDVM and in case of error it waits forever.

I: 2021-06-27 16:19:37.452 Loaded 194239 IDs to lookup table - /usr/local/etc/DMRIds.dat
E: 2021-06-27 16:19:37.458 No reply from the modem for some time, resetting it
E: 2021-06-27 16:19:37.458 No reply from the modem for some time, resetting it
M: 2021-06-27 16:19:37.458 Closing the MMDVM
M: 2021-06-27 16:19:39.459 Opening the MMDVM

**Comment by iddq** [comment]
```
(gdb) bt
#0  0x76cac664 in __GI___select (nfds=5, readfds=0x7e9a4450, writefds=0x0, exceptfds=0x0, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00074d3c in CSerialController::read (this=0xb86640, buffer=0xb8b48b "F", length=10) at SerialController.cpp:382
#2  0x00049358 in CModem::getResponse (this=0xb85be0) at Modem.cpp:1780
#3  CModem::readVersion (this=0xb85be0) at Modem.cpp:1462
#4  0x0004b3b4 in CModem::open (this=0xb85be0) at Modem.cpp:295
#5  0x0004b86c in CModem::clock (this=0xb85be0, ms=6065) at Modem.cpp:375
#6  0x00043480 in CMMDVMHost::run (this=this@entry=0xb85180) at MMDVMHost.cpp:988
#7  0x00012f70 in main (argc=<optimized out>, argv=<optimized out>) at MMDVMHost.cpp:105
```
